version: "3.8"

services:
  #######################
  # BACKGROUND SERVICES #
  #######################
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./docker/db/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "jeral"
      MONGO_INITDB_ROOT_PASSWORD: "1234"
  postgres_users_db:
    container_name: postgres_users_db_container
    image: postgres:13.22-alpine3.21
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=jeral
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./docker/db/postgres_users_db:/var/lib/postgresql/data
  postgres_keycloak_db:
    container_name: postgres_keycloak_db_container
    image: postgres:13.22-alpine3.21
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak_password
    volumes:
      - ./docker/db/postgres_keycloak_db:/var/lib/postgresql/data

  ####################
  # MANAGED SERVICES #
  ####################
  mongo_express:
    container_name: mongo_express_container
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "jeral"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "1234"
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_AUTH_DATABASE: "admin"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: yohan #For browser
      ME_CONFIG_BASICAUTH_PASSWORD: 1234 #For browser
    volumes:
      - ./docker/ms/mongo-express:/config
    depends_on:
      - mongodb
  pgAdmin:
    container_name: pgadmin_container
    image: elestio/pgadmin:latest
    restart: always
    ports:
      - "5433:5433"
    environment:
      - PGADMIN_DEFAULT_EMAIL=jeral@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
      - PGADMIN_LISTEN_PORT=5433
    volumes:
      - ./docker/ms/pgAdmin:/var/lib/pgadmin
    depends_on:
      - postgres_users_db
      - postgres_keycloak_db
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    command:
      - start-dev
    ports:
      - "8070:8080"

  #######################
  # APPLICATION SERVICES #
  #######################
  user_service:
    image: jeralsandeeptha/url-shortner-user-service-develop:895e4f1d417e88d8a1da57e02386585ff3624734
    container_name: user_service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - NODE_ENV=production
      - KEYCLOACK_SERVER_URL=http://keycloak:8080
      - KEYCLOACK_GATEWAY_SERVER_URL=http://gateway_service:5000/gateway/auth
      - KEYCLOACK_CLIENT_ID=url-shortner-user-service
      - KEYCLOACK_CLIENT_SECRET=PeoQEM1Dj16coUpGBp1Xhx7Puykf6ELU
      - DATABASE_URL=postgresql://jeral:1234@postgres_users_db:5432/users_db
      - BASE_URL=http://localhost
      - DOMAIN=undefined # not use sub domains, This is for kubernates
    depends_on:
      - postgres_users_db
  url_generate_service:
    image: jeralsandeeptha/url-shortner-url-generate-service-main:6241a82e13207ee357f48a1f08343dc897b7aa92
    container_name: url_generate_service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - NODE_ENV=production
      - DATABASE_URL=mongodb://jeral:1234@mongodb:27017/url_generate_db?authSource=admin
      - BASE_URL=http://localhost
    depends_on:
      - mongodb
  redirection_service:
    image: jeralsandeeptha/url-shortner-url-redirect-service-main:ff117e3d98a1147642b6d03dff725c2b4900310f
    container_name: redirection_service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - NODE_ENV=production
      - DATABASE_URL=mongodb://jeral:1234@mongodb:27017/url_generate_db?authSource=admin
      - BASE_URL=http://localhost
    depends_on:
      - mongodb
  gateway_service:
    image: jeralsandeeptha/url-shortner-gateway-service-main:b61521631d3f6b64fe72fa886908267fecd86daf
    container_name: gateway_service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - USER_API_URL=http://user_service:5001
      - URL_GENERATE_API_URL=http://url_generate_service:5002
      - URL_REDIRECT_API_URL=http://redirection_service:5003
      - KEYCLOAK_API_URL=http://keycloak:8080
      - BASE_URL=http://localhost
    depends_on:
      - user_service
      - url_generate_service
      - redirection_service
      - keycloak
      - frontend
  frontend:
    image: jeralsandeeptha/url-shortner-frontend-service-main:bf2317351e6cae5ddd58eb2bdd77114bbba1abe6
    container_name: frontend_url_shortner
    restart: always
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
      - MODE=production
      - VITE_API_URL=http://localhost:5000
      - VITE_DOMAIN=http://localhost # not use sub domains, This is for kubernates